# Generated by Django 3.0.2 on 2020-04-22 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_number', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=20)),
                ('purpose', models.CharField(choices=[('Reviewing', 'Select purpose...'), ('Editing Code', 'Editing Code'), ('Editing Document', 'Editing Document'), ('Review', 'Review'), ('Duty', 'Duty')], default='general', max_length=20)),
                ('pc', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('timeout', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
